#!/usr/bin/env bash
# Bash script that will display information about subdomains
domain () {
if [ "$2" ];
then
    echo -n "The subdomain $2 is a"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print "
